 /******************************************************************************
 *
 * Module: UltraSonic Sensor (HC-SR04)
 *
 * File Name: ultra_sonic_sensor.h
 *
 * Description: header file for UltraSonic Sensor (HC-SR04) driver.
 *
 * Author: Bassam Ashraf
 *
 *******************************************************************************/

#ifndef SRC_ULTRA_SONIC_SENSOR_H_
#define SRC_ULTRA_SONIC_SENSOR_H_

#include "std_types.h"	/* To use type deceleration for variables */

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define ULTRASONIC_SENSOR_ECHO_PORT_ID                 	PORTD_ID
#define ULTRASONIC_SENSOR_ECHO_PIN_ID                  	PIN6_ID

#define ULTRASONIC_SENSOR_TRIGGER_PORT_ID               PORTD_ID
#define ULTRASONIC_SENSOR_TRIGGER_PIN_ID                PIN7_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description :
 * Function Initialize the ICU driver as required.
 * Set up the ICU callback function.
 * Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void);


/*
 * Description :
 * Send the trigger pulse to the UltraSonic sensor.
 */
void Ultrasonic_Trigger(void);


/*
 * Description :
 * Function Send the trigger pulse by using the Ultrasonic_Trigger function.
 * Start the measurement process via the ICU driver.
 * Return: The measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void);


/*
 * Description :
 * Function This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by the UltraSonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* SRC_ULTRA_SONIC_SENSOR_H_ */
